In [6]:
from tensorflow.keras.layers import LSTM, Dense, Dropout, Attention #Maybe add an Attention mechanism?
from tensorflow.keras.models import Sequential
from tensorflow.keras.metrics import mean_squared_error
import numpy as np

In [7]:
numberOfSteps = 5
numberOfFeatures = 3

model = Sequential()


model.add(
    LSTM(20, activation='relu', input_shape=(numberOfSteps, numberOfFeatures))
)
model.add(Dropout(0.2))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='linear'))

model.compile(optimizer='adam', loss='mse', metrics=[mean_squared_error])

In [8]:
dataset = np.array([[i] * numberOfFeatures for i in range(1, 500 + 1)])
print(dataset)

def gety(x):
    return 4 * np.sin(x[0]) + 3*np.cos(x[1]) +2*np.tan(x[2])

y = np.zeros(len(dataset))
for i in range(len(y)):
    y[i] = gety(dataset[i])

dataset = np.expand_dims(dataset, axis=1)

[[  1   1   1]
 [  2   2   2]
 [  3   3   3]
 ...
 [498 498 498]
 [499 499 499]
 [500 500 500]]


In [9]:

model.fit(dataset, y, epochs=10, batch_size=50)

Epoch 1/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 968.7270 - mean_squared_error: 968.7270
Epoch 2/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1524.4110 - mean_squared_error: 1524.4110
Epoch 3/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 941.8892 - mean_squared_error: 941.8892
Epoch 4/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2313.1067 - mean_squared_error: 2313.1067 
Epoch 5/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1277.4617 - mean_squared_error: 1277.4617
Epoch 6/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1365.1176 - mean_squared_error: 1365.1176
Epoch 7/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 627.6674 - mean_squared_error: 627.6674
Epoch 8/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2236.4670 - mean_squared_error: 2236.4670 
Epoch 9/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 540.8858 - mean_squared_error: 540.8858
Epoch 10/10
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1343.7285 - mean_squared_error: 1343.7285


In [11]:
preds = np.array([[i] * numberOfFeatures for i in range(495, 560 + 1)])
preds = np.expand_dims(preds, axis=1)
model.predict(preds)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 956ms/step


array([[-0.1465793 ],
       [-0.24207151],
       [-0.34707955],
       [-0.45875558],
       [-0.5744056 ]], dtype=float32)